/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_Ragnarok_NativeFilterFunc */

#ifndef _Included_cn_Ragnarok_NativeFilterFunc
#define _Included_cn_Ragnarok_NativeFilterFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    lightFilter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_lightFilter
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    lomoAddBlckRound
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_lomoAddBlckRound
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    neonFilter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_neonFilter
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    oilFilter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_oilFilter
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc#
 * Method:    tvFilter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_tvFilter
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    averageSmooth
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_averageSmooth
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    hdrFilter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_hdrFilter
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    discreteGaussianBlur
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_discreteGaussianBlur
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    softGlow
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_softGlow
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     cn_Ragnarok_NativeFilterFunc
 * Method:    sketchFilter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_Ragnarok_NativeFilterFunc_sketchFilter
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
